### ISSUE TITLE
枣子哥，我更新了ComfyUI之后这个插件坏了QAQ

### ISSUE THREAD

**Issue by CBook424** [ZHO-ZHO-ZHO/ComfyUI-SVD-ZHO#2]
报错内容如下，请问有什么解决办法吗？
Traceback (most recent call last):
  File "F:\ComfyUI10.24\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI10.24\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-I2VGenXL\__init__.py", line 1, in <module>    from .I2VGenXL import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\ComfyUI10.24\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-I2VGenXL\I2VGenXL.py", line 9, in <module>    from diffusers import I2VGenXLPipeline
ImportError: cannot import name 'I2VGenXLPipeline' from 'diffusers' (F:\ComfyUI10.24\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\__init__.py)

Cannot import F:\ComfyUI10.24\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-I2VGenXL module for custom nodes: cannot import name 'I2VGenXLPipeline' from 'diffusers' (F:\ComfyUI10.24\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\__init__.py)

**Comment by jimwang2019** [comment]
update your diffusers version.
